runtime: nodejs16
env: standard
service: default
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
# env:
  # SEND_GRID_KEY: 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
