runtime: nodejs16 
env: standard
service: default
# instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10